import unittest
import time
import os
from src.trading_system.core.backtest_runner import BacktestRunner
from src.trading_system.strategies.atr_trend_strategy import ATRTrendStrategy

class TestATRTrendLifecycle(unittest.TestCase):
    def setUp(self):
        self.csv_path = "breakout_test_data.csv"
        # Ensure data exists (already generated by previous step)
        if not os.path.exists(self.csv_path):
             from generate_breakout_test_data import generate_breakout_data
             generate_breakout_data(self.csv_path)

    def test_full_lifecycle(self):
        """Verify Entry, Unit Sizing, and ATR Stop Loss exit."""
        runner = BacktestRunner(
            strategy_class=ATRTrendStrategy,
            symbol="TEST",
            csv_path=self.csv_path,
            strategy_params={
                "atr_period": 14,
                "breakout_period": 20,
                "risk_pct": 0.01,
                "atr_multiplier": 2.0,
                "max_equity_pct": 0.05
            },
            initial_capital=100000.0,
            enable_risk_management=False # We use the strategy's built-in ATR risk
        )
        
        runner.run()
        
        # In breakout_test_data.csv:
        # 1. First 20 bars range 95-105. High=105.
        # 2. Bar 21: Close 110 (Breakout). 
        #    ATR calculation will happen. Unit size will be calculated.
        # 3. Bar 22: Low 85. This should trigger the ATR Stop Loss set at Entry.
        
        # Verify that at least one trade occurred
        # Account should have less cash than initial (if loss) or positions closed
        self.assertEqual(runner.account_service.get_position("TEST").quantity, 0)
        # 100,000 - loss from the trade
        self.assertLess(runner.account_service.cash, 100000.0)
        
        print(f"Final Cash: {runner.account_service.cash}")

if __name__ == "__main__":
    unittest.main()
