import logging
import queue
import threading
from datetime import datetime
from typing import Callable, Dict, List, Any

from src.trading_system.core.event_types import Event, _EVENT_PRIORITY

logger = logging.getLogger(__name__)

# Sentinel used to unblock the dispatch thread on stop()
_SENTINEL = None

# A timestamp guaranteed to sort *after* any real event timestamp.
_EPOCH_MAX = datetime.max


class _PrioritizedEvent:
    """Wrapper that makes Events comparable for use in a PriorityQueue.

    Sort key: (timestamp, event_type_priority, sequence_number)
    - timestamp           - logical simulation time; None events sort last.
    - event_type_priority - within the same timestamp, MARKET < SIGNAL < ORDER < FILL.
    - sequence_number     - tie-break to preserve insertion order within the
                            same (timestamp, type) bucket.
    """

    __slots__ = ("event", "timestamp", "type_priority", "seq")

    def __init__(self, event, seq: int):
        self.event = event
        self.seq = seq
        if event is _SENTINEL:
            # Sentinel sorts last so real events are always drained first.
            self.timestamp = _EPOCH_MAX
            self.type_priority = 999
        else:
            self.timestamp = event.timestamp or _EPOCH_MAX
            self.type_priority = _EVENT_PRIORITY.get(event.type, 50)

    def _sort_key(self):
        return (self.timestamp, self.type_priority, self.seq)

    def __lt__(self, other): return self._sort_key() < other._sort_key()
    def __le__(self, other): return self._sort_key() <= other._sort_key()
    def __eq__(self, other): return self._sort_key() == other._sort_key()
    def __gt__(self, other): return self._sort_key() > other._sort_key()
    def __ge__(self, other): return self._sort_key() >= other._sort_key()


class EventEngine:
    """
    Event-driven engine that manages an event queue and dispatches events
    to registered callback handlers.

    Two dispatch modes
    ------------------
    time_ordered=False (default - original behaviour)
        Events are dispatched in FIFO order, exactly as before.  Use this
        for live trading where events arrive in real time.

    time_ordered=True
        Events are placed in a min-heap priority queue and dispatched in
        ascending (timestamp, event_type_priority, insertion_order) order.
        This faithfully reproduces the causal sequence of a backtest:

            bar1 @10:00  ->  signal @10:00 (generated by bar1)
                         ->  order  @10:00
                         ->  fill   @10:00
            EndOfBar     @10:00
            bar2 @10:05  ->  ...

        Events without a timestamp sort after all timestamped events
        but before the stop-sentinel, and among themselves preserve FIFO order.

    Thread-safety
    -------------
    - register() / unregister() are safe from any thread.
    - _handlers is protected by _lock; dispatch iterates a snapshot.
    - task_done()/join() semantics are preserved so stop() waits for all
      in-flight events before returning.
    """

    def __init__(self, time_ordered: bool = True):
        """
        Parameters
        ----------
        time_ordered : bool
            If True (default), use a priority queue sorted by event timestamp.
            If False, use a plain FIFO queue.
        """
        self._time_ordered = time_ordered
        self._queue: queue.Queue = (
            queue.PriorityQueue() if time_ordered else queue.Queue()
        )
        self._seq = 0                           # monotonic counter for tie-breaking
        self._seq_lock = threading.Lock()       # protects _seq

        self._handlers: Dict[str, List[Callable]] = {}
        self._lock = threading.RLock()          # protects _handlers
        self._active = False
        self._thread = threading.Thread(target=self._run, daemon=True)

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self):
        """Start the event engine background thread."""
        if self._thread.is_alive():
            return
        self._active = True
        if not self._thread.is_alive():
            self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def stop(self):
        """Stop the event engine.

        Waits for all events currently in the queue to be fully processed
        before returning, then joins the background thread.
        """
        self._queue.join()
        self._active = False
        self.put(_SENTINEL)      # sentinel to unblock queue.get()
        self._thread.join()

    # ------------------------------------------------------------------
    # Event production
    # ------------------------------------------------------------------

    def put(self, event):
        """Enqueue an event for dispatch.

        In time_ordered mode the event is wrapped in a _PrioritizedEvent so
        the PriorityQueue can order it correctly.  In FIFO mode the event is
        enqueued as-is (original behaviour).
        """
        if self._time_ordered:
            with self._seq_lock:
                seq = self._seq
                self._seq += 1
            self._queue.put(_PrioritizedEvent(event, seq))
        else:
            self._queue.put(event)

    # ------------------------------------------------------------------
    # Handler registration
    # ------------------------------------------------------------------

    def register(self, event_type: str, handler: Callable):
        """Register a handler for a specific event type (thread-safe)."""
        with self._lock:
            if event_type not in self._handlers:
                self._handlers[event_type] = []
            if handler not in self._handlers[event_type]:
                self._handlers[event_type].append(handler)

    def unregister(self, event_type: str, handler: Callable):
        """Unregister a handler (thread-safe)."""
        with self._lock:
            if event_type in self._handlers:
                try:
                    self._handlers[event_type].remove(handler)
                except ValueError:
                    pass

    # ------------------------------------------------------------------
    # Internal run-loop
    # ------------------------------------------------------------------

    def _run(self):
        """Background thread: dequeue and dispatch events."""
        while True:
            try:
                item = self._queue.get(timeout=1.0)
            except queue.Empty:
                if not self._active:
                    break
                continue

            try:
                # Unwrap priority wrapper when in time_ordered mode
                event = item.event if self._time_ordered else item

                if event is _SENTINEL:
                    self._queue.task_done()
                    break
                self._dispatch(event)
            finally:
                try:
                    self._queue.task_done()
                except ValueError:
                    pass

    def _dispatch(self, event: Event):
        """Dispatch an event to all registered handlers (snapshot-safe)."""
        with self._lock:
            handlers = list(self._handlers.get(event.type, []))

        for handler in handlers:
            try:
                handler(event)
            except Exception:
                logger.exception(
                    "Unhandled exception in handler %s for event type '%s'",
                    getattr(handler, '__qualname__', repr(handler)),
                    event.type,
                )
